### PR TITLE
Automatically generate an accurate changelog.

### PR DESCRIPTION
**Pull request by drupol**
Hi,

This is something rather experimental.

It's a package that I did sometime ago, and I was surprised that it was still working fine.

To test it:

1) Create a basic Github token at: https://github.com/settings/tokens
2) Create a file `taskman.yml` at the root of the project with the content:

```yaml
github:
  token: [the-new-github-token]
```
3) Run: `./vendor/bin/taskman github:changelog`

Let me know what you think.

The result is like this:

# Change Log

## [1.5.0](https://github.com/gravataLonga/container/tree/1.5.0) (2020-05-10)
[Full Changelog](https://github.com/gravataLonga/container/compare/1.4.2...1.5.0)

**Merged pull requests:**

- Let callable type be used. [\#4](https://github.com/gravataLonga/container/pull/4) ([drupol](https://github.com/drupol))
- Minor cleanup, minor optimizations and simplifications. [\#3](https://github.com/gravataLonga/container/pull/3) ([drupol](https://github.com/drupol))

## [1.4.2](https://github.com/gravataLonga/container/tree/1.4.2) (2020-05-10)
[Full Changelog](https://github.com/gravataLonga/container/compare/1.4.1...1.4.2)

**Merged pull requests:**

- Move some files around. [\#2](https://github.com/gravataLonga/container/pull/2) ([drupol](https://github.com/drupol))

## [1.4.1](https://github.com/gravataLonga/container/tree/1.4.1) (2020-05-09)
[Full Changelog](https://github.com/gravataLonga/container/compare/1.4.0...1.4.1)

**Merged pull requests:**

- Use drupol/php-conventions [\#1](https://github.com/gravataLonga/container/pull/1) ([drupol](https://github.com/drupol))

## [1.4.0](https://github.com/gravataLonga/container/tree/1.4.0) (2020-05-06)
[Full Changelog](https://github.com/gravataLonga/container/compare/1.3.1...1.4.0)

## [1.3.1](https://github.com/gravataLonga/container/tree/1.3.1) (2020-05-05)
[Full Changelog](https://github.com/gravataLonga/container/compare/1.3.0...1.3.1)

## [1.3.0](https://github.com/gravataLonga/container/tree/1.3.0) (2020-05-03)
[Full Changelog](https://github.com/gravataLonga/container/compare/1.2.1...1.3.0)

## [1.2.1](https://github.com/gravataLonga/container/tree/1.2.1) (2020-05-03)
[Full Changelog](https://github.com/gravataLonga/container/compare/1.2.0...1.2.1)

## [1.2.0](https://github.com/gravataLonga/container/tree/1.2.0) (2020-04-30)
[Full Changelog](https://github.com/gravataLonga/container/compare/1.1.0...1.2.0)

## [1.1.0](https://github.com/gravataLonga/container/tree/1.1.0) (2020-04-19)
[Full Changelog](https://github.com/gravataLonga/container/compare/1.0.0...1.1.0)

## [1.0.0](https://github.com/gravataLonga/container/tree/1.0.0) (2020-04-18)

\* *This Change Log was automatically generated by [github_changelog_generator](https://github.com/skywinder/Github-Changelog-Generator)*

### CODE REVIEW

**Comment by drupol** [comment]
Let me know what you think @gravataLonga

**Comment by gravataLonga** [comment]
Need to read all the source code, because of the token. Let me investigate.

**Comment by drupol** [comment]
FYI: There is no need to set any permission on the token!

**Comment by gravataLonga** [comment]
As far i can understand this library is a wrapper of ruby library, i liked this. Give me more time then i will know for sure how this all work. 👍

**Comment by drupol** [comment]
I will also take time to update PHP Taskman, it's been a while that I haven't updated it.

Wait & see.

**Comment by gravataLonga** [comment]
Nah, i prefer to updated manually.

**Pull request closed without merging**
