### PR TITLE
Use drupol/php-conventions

### PR DESCRIPTION
**Pull request by drupol**
Hi,

Here are a few improvements using [drupol/php-conventions](https://github.com/drupol/php-conventions/).

This is a package that helps you enable some preconfigured checking tools for your library. Very helpful on many projects of mine and at work.

## Description

* Minimum PHP version is now 7.1.3
* Updated Github Actions CI.
* Enable PSalm (level 7, totally typed)
* Enable PHPStan (level 8)
* Fix code style
* Enable Infection
* Normalize composer.json
* Fixed small issues in the code
* Enable GrumPHP

See it in action, run

`./vendor/bin/grumphp run`

```
$ ./vendor/bin/grumphp run                                                                                                                                                          GrumPHP is sniffing your code!
Running task  1/14: SecurityChecker... ✔
Running task  2/14: Composer... ✔
Running task  3/14: ComposerNormalize... ✔
Running task  4/14: YamlLint... ✔
Running task  5/14: JsonLint... ✔
Running task  6/14: PhpLint... ✔
Running task  7/14: TwigCs... ✔
Running task  8/14: PhpCsAutoFixerV2... ✔
Running task  9/14: PhpCsFixerV2... ✔
Running task 10/14: Phpcs... ✔
Running task 11/14: Psalm... ✔
Running task 12/14: PhpStan... ✔
Running task 13/14: Phpunit... ✔
Running task 14/14: Infection... ✔
$
```

Hope you like it!

### CODE REVIEW

**Comment by gravataLonga** [comment]
This pull request is making so many change,   
```https://github.com/gravataLonga/container/pull/1/commits/b61a524a6ec2893c7a7fc1cb2a99a95ce322224d``` why this change? 

This pull request is for promoting your software, or is a genuine pull request?

**Comment by drupol** [comment]
> https://github.com/gravataLonga/container/pull/1/commits/b61a524a6ec2893c7a7fc1cb2a99a95ce322224d

Hi,

Indeed, it's a lot of good changes :)

No, I don't promote anything, [drupol/php-conventions](https://github.com/drupol/php-conventions) is itself not a "real" package but merely a set of pre-configured tools to use when developing in PHP and I though that it might be helpful for you. I really like your container.

The change in the CI is from my default CI configuration. It enable PHP 7.1 and also enable caching for composer to speed up builds.

**Comment by gravataLonga** [comment]
It's done.

**Comment by gravataLonga** [comment]
@drupol  One last thing, your library not work on last composer version.   

```
Problem 1
    - phpro/grumphp v0.16.2 requires composer-plugin-api ~1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - phpro/grumphp v0.17.2 requires composer-plugin-api ~1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - drupol/php-conventions 1.7.0 requires phpro/grumphp ^0.16.2 || ^0.17.2 -> satisfiable by phpro/grumphp[v0.17.2, v0.16.2].
    - Root composer.json requires drupol/php-conventions ^1.7 -> satisfiable by drupol/php-conventions[1.7.0].

You are using a snapshot build of Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report an issue to them to ask them to support Composer 2. To work around this you can run Composer with --ignore-platform-reqs, but this will also ignore your PHP version and may result in bigger problems down the line.
```

**Comment by drupol** [comment]
Yes, as long as composer 2 is not stable, it won't work unfortunately.

**Comment by drupol** [comment]
Hey thanks for merging !

**Comment by gravataLonga** [comment]
Yeah, soon or later you will work on that, i'm sure.

**Pull request merged**
