### PR TITLE
Move some files around.

### PR DESCRIPTION
**Pull request by drupol**
## Description

I removed some files from the root of the project.

## Motivation and context

There is no need to keep Github specific files at the root of the project, we can move them in `.github` directory.

### CODE REVIEW

**Comment by gravataLonga** [comment]
You are right, i'm planning to support `aliases` and `extend` maybe can implement later on. :)  
Thank for this! 👍

**Comment by drupol** [comment]
Can't wait to see next things :)

**Comment by gravataLonga** [comment]
Merged! :) Thank for your contribution, keep it coming ;)

**Comment by drupol** [comment]
Definitely :D

**Pull request merged**
