### PR TITLE
Let callable type be used.

### PR DESCRIPTION
**Pull request by drupol**
## Description

Add a feature, let callable type be used in `::set()` and `::factory()`.

`::set()` is now a real alias of `::factory()`.

```php
$container = new Container();

 $class = new class {
            public function get(): int
            {
                return mt_rand(0, 100);
            }
        };

$container->factory('random', [$class, 'get']);
$container->get('random'); // random int
```

### CODE REVIEW

**Comment by gravataLonga** [comment]
Holy shit.. that is been in back my mind long time! 👍 Yes sir. I will merge that!

**Comment by drupol** [comment]
Hold on, rebasing ;)

**Comment by gravataLonga** [comment]
Don't worry man, i'm make some change also.

**Comment by gravataLonga** [comment]
It's not passing on php 7.1 but isn't you fault, i'm making some new feature also. (Alias). But i already fixed that. :).

**Comment by drupol** [comment]
Great! :D

**Comment by gravataLonga** [comment]
Release 1.5.0 👍 I'm anxious to use this on my private projects. Thank for you support!

**Pull request merged**
